### ISSUE TITLE
Cannot locate the Nuget package

### ISSUE THREAD

**Issue by ivoloshin** [louisfischer/Cake.EntityFramework#1]
I'm having trouble using your plugin. If I use the following:

`#addin "Cake.EntityFramework6"`

I get this error:

`Could not find any assemblies compatible with .NETFramework,Version=v4.5.`

So, I looked on nuget.com and couldn't find the package.

Thanks,
Ilya

**Comment by Silvenga** [comment]
Simply, I've never published it. 

I haven't gotten enough testing under production environments so I rather not encourage its usage as of yet. If you want, I can publish it to a private feed.

**Comment by ivoloshin** [comment]
That's okay, thank you. I'll go the command line route and keep a lookout for when you feel it's ready for some sort of alpha release. 👍
