### ISSUE TITLE
Publish to Nuget

### ISSUE THREAD

**Issue by louisfischer** [louisfischer/Cake.EntityFramework#2]
I was looking for an exact project like this for Cake and Entity Framework 6. I looked on Nuget and could not find any packages that reference the project name. Are you actively working on this project? If not, are you looking for a Maintainer? I did not want to reinvent a plugin if one has already be created.

**Comment by Silvenga** [comment]
Kind of sad, I never really was able to dogfood this project - my team kind of moved away from CakeBuild. This type of library is somewhat critical and I wouldn't feel confident in releasing it into the wild if it may kill people (or databases). With that said, I don't know of any reason why it would fail that badly, I just need testing. 

If you want to take up the reins I'm totally open to this, and I can totally help out if needed.

**Comment by louisfischer** [comment]
I am more than willing to take over the project. I already created two plugins for cake and am need for something like this. It would be nice to not have to start from scratch.. Let me know if you want to transfer the repository to me. Eventually, i would like to transfer it to the Cake Contributions Organizations once all the tests and additional features are added.

**Comment by Silvenga** [comment]
Done, I would like to maintain collaboration access though.

EDIT: I have a subscription via Appveyor for OSS, I'm hoping that transfers correctly.

**Comment by louisfischer** [comment]
no problem...Thanks for the opportunity to work on it
