### ISSUE TITLE
Seed method is not run if no migrations are run

### ISSUE THREAD

**Issue by PaigeM89** [louisfischer/Cake.EntityFramework#26]
When migrating to latest, if there are no pending migrations to apply, the migrate call is skipped entirely. This causes the seed method to get skipped, so data updates or changes to just the seed data are not applied if there is no migration.

This primarily revolves around how we handle the MigrateTo call and avoid passing in a null. I wonder if we can expose the seed method directly and allow that to get called, either in the MigrateToLatest or even in the consuming script directly.

Do we want seed methods always run, or should that be in a flag the user can set in the options, so they can enable seed method running even if no migrations are applied?

**Comment by louisfischer** [comment]
I like the idea of adding a separate method to run the seed method. That way it can be combined with a Pending Migrations check. Want to take a shot at a pull request?

**Comment by PaigeM89** [comment]
Yeah I'll try to get a PR for this as soon as I can.

**Comment by PaigeM89** [comment]
Hmmm - some digging through the EF seems to indicate that the seed method isn't exposed on the DbMigrator. The `SeedDatabase()` method is internal.

If we make an explicit function for running seed methods, I think it will still need to run migrations behind the scenes. The other choice is to change the database update in Cake to always update the database and put in more checks to avoid passing a null migration.
