### ISSUE TITLE
Update icon with new cake-contrib icon

### ISSUE THREAD

**Issue by louisfischer** [louisfischer/Cake.EntityFramework#28]
Update the Nuget icon with the new cake-contribution icon. See blog post below

http://cakebuild.net/blog/2017/06/new-cake-contrib-icon

**Comment by gep13** [comment]
Recommended url is https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png

**Comment by devlead** [comment]
Perhaps update graphics repo Readme with that guidance and link to blog post.

**Comment by gep13** [comment]
@devlead yes, that is a good idea. I will get that done.

**Comment by gep13** [comment]
@devlead I have added information to the graphics repo about recommendations for URL usage.
