### ISSUE TITLE
Load ConnectionString, ConnectionProvider from App Config

### ISSUE THREAD

**Issue by PaigeM89** [louisfischer/Cake.EntityFramework#4]
It would be nice to not have to maintain the connection string in the cake file when we can already pull that from the AppConfig that is loaded. I've got this working locally by specifying the `ConnectionName` in the settings instead, and using that to load the correct connection information.

**Comment by Silvenga** [comment]
Agreed, however, `ConnectionProvider` adds some complexity (just not really under MSSQL). Maybe parse a config file for `EfMigratorSettings`.

**Comment by PaigeM89** [comment]
Hm. I have no experience with EF when it's not using SQL server, so I don't know what additional issues might be caused with the provider stuff.

From the PostgresQL test project, the connection string is just this:
`<add name="SchoolContext" connectionString="{the actual connection string}" providerName="Npgsql"/>`, so I'm just pulling out the values of the connection string and provider name based on the provided Connection Name. I do need to clean up my implementation, but if this approach won't always work then I think we'll have to find a different approach.
