### ISSUE TITLE
Standardize Deployment to Nuget

### ISSUE THREAD

**Issue by louisfischer** [louisfischer/Cake.EntityFramework#9]
Review and standardize Deployment to nuget using the Cake.Reciepe repo that other cake plugins are using. This includes code coverage, automated test runs, and Deployment to Nuget via AppVeyor

**Comment by Silvenga** [comment]
Throughts:

- Project is called `Cake.EntityFramework6`
  - We might want three different packages - EF6, EFCore1, Common
- No released version yet, I propose:
  - Starting with `-alpha` under Semantic Versioning

**Comment by louisfischer** [comment]
What do you think about using Gitflow?
Master would be the copy that gets deployed.

I created a develop branch

**Comment by Silvenga** [comment]
Damn, you blocked my commit to fix the build.

Never really liked true Gitflow - could we transpose where master is upstream and stable is what is deployed?

**Comment by Silvenga** [comment]
How about GitHubFlow? - http://scottchacon.com/2011/08/31/github-flow.html

- Anything in the master branch is deployable
- To work on something new, create a descriptively named branch off of master (ie: new-oauth2-scopes)
- Commit to that branch locally and regularly push your work to the same named branch on the server
- When you need feedback or help, or you think the branch is ready for merging, open a pull request

There's a lot of ceremony in GitFlow, much of which doesn't integrate into UI's and doesn't work well under Windows. It also breaks Git defaults (IMHO) and increases conceptual overhead.

**Comment by louisfischer** [comment]
Works for me....I like githubflow. How about using tags when deploying to Nuget?

**Comment by Silvenga** [comment]
I like that, makes it easy for Appveyor to know what to deploy to what. What do you think, tags = nuget release versions?

**Comment by louisfischer** [comment]
Yep. The Tag will equal the version number. BTY, I use [gitkraken ](https://www.gitkraken.com/) for windows. It makes work with git super simple and has a nice GUI front end. 
If you it is ok, I will go ahead and get rid of the develop branch and just use feature branches.. I will merge what is in develop to master then drop the  branch.

**Comment by Silvenga** [comment]
Thanks @louisfischer!
